- run:
    name: Debug SSH connectivity
    command: |
      set -x
      echo "HOST=$CENTOS_HOST USER=$CENTOS_USER"
      nc -vz $CENTOS_HOST 22 || true
      ssh -o ConnectTimeout=10 -v ${CENTOS_USER}@${CENTOS_HOST} "echo ok"



